# Generated by Django 2.2.1 on 2019-05-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190515_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
