# Generated by Django 2.2.1 on 2019-05-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190515_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='Teacher',
            field=models.ManyToManyField(to='app01.Teacher'),
        ),
    ]
