# Generated by Django 2.2.1 on 2019-05-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20190515_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='Teacher',
            new_name='teacher',
        ),
    ]
