# Generated by Django 2.2.1 on 2019-05-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
