# Generated by Django 2.2.1 on 2019-05-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to='app01.User')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n', to='app01.News')),
            ],
        ),
    ]
