# Generated by Django 2.2.1 on 2019-05-25 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_favor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='favor',
        ),
    ]
