# Generated by Django 2.2.1 on 2019-05-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_news_favor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favor',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='news',
            name='favor',
            field=models.ManyToManyField(through='app01.Favor', to='app01.User'),
        ),
    ]
