# Generated by Django 2.2.1 on 2019-05-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190526_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='evil',
            field=models.ManyToManyField(to='app01.Evil'),
        ),
    ]
