# Generated by Django 2.2.1 on 2019-05-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('stime', models.DateTimeField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_created=True)),
                ('username', models.CharField(db_index=True, max_length=32)),
                ('email', models.EmailField(max_length=32, unique=True)),
                ('pwd', models.CharField(max_length=64)),
            ],
            options={
                'unique_together': {('username', 'pwd')},
                'index_together': {('username', 'pwd')},
            },
        ),
    ]
