# Generated by Django 2.2.1 on 2019-05-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chouti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=32)),
                ('praise_count', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('count', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='pwd',
            new_name='password',
        ),
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together={('username', 'password')},
        ),
        migrations.AlterIndexTogether(
            name='userinfo',
            index_together={('username', 'password')},
        ),
    ]
