# Generated by Django 2.2.1 on 2019-05-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190522_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chouti',
        ),
    ]
