# Generated by Django 2.2.1 on 2019-05-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_delete_chouti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chouti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=32)),
                ('praise_count', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('count', models.CharField(max_length=32)),
            ],
        ),
    ]
