# Generated by Django 2.2.1 on 2019-05-23 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_chouti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chouti',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo'),
        ),
    ]
