# Generated by Django 2.2.1 on 2019-05-23 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_chouti_favor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chouti',
            name='favor',
        ),
        migrations.AddField(
            model_name='chouti',
            name='favor',
            field=models.ManyToManyField(to='app01.UserInfo'),
        ),
        migrations.AlterField(
            model_name='chouti',
            name='username',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(max_length=16, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Chouti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo')),
            ],
        ),
    ]
