# Generated by Django 2.2.1 on 2019-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20190523_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chouti',
            name='content',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
