# Generated by Django 2.2.1 on 2019-05-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_remove_chouti_favor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chouti',
            name='favor',
            field=models.ManyToManyField(to='app01.UserInfo'),
        ),
    ]
