# Generated by Django 2.2.1 on 2019-05-23 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_chouti_favor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(max_length=16, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Chouti')),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='app01.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo')),
            ],
        ),
    ]
