# Generated by Django 2.2.1 on 2019-05-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_remove_chouti_favor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favor', models.CharField(max_length=32)),
                ('Chouti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Chouti')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo')),
            ],
        ),
    ]
