# Generated by Django 2.2.1 on 2019-06-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_auto_20190601_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chouti',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
