# Generated by Django 2.2.1 on 2019-06-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_auto_20190602_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.CharField(max_length=64),
        ),
    ]
